### PR TITLE
[bento 2.11] permissioned docker image

### PR DESCRIPTION
**Pull request by davidlougheed**
this'll conflict with other branches potentially

### CODE REVIEW

**Review by gsfk — COMMENTED** [review]
Prod container works as expected. 

Dev container had trouble with the startup script: 
```
bentov2-beacon  | [bento_base_image] [/create_service_user.bash] using USER_ID=1000
bentov2-beacon  | bash: ./run.dev.bash: No such file or directory
```
Hard to debug since container immediately dies. Looks like a mismatch between expected directory and actual WORKDIR.


Also: 
- is it possible that permissions were required only for the dev container? Or are the permissions different between prod and dev containers?

**Comment by davidlougheed** [comment]
this might have happened if in a branch where `run.dev.bash` didnt exist locally - i've added it to the container as a backup and maybe? thatll help

**Comment by davidlougheed** [comment]
ok, the new dev image I think will work when tried in combination with the `final-docker-updates` bv2 branch

**Comment by gsfk** [comment]
getting closer.... but now hot reload is broken. Possibly another VS code issue.

**Review by gsfk — APPROVED** [review]

**Pull request merged**
