### PR TITLE
Fixes/patch dats default

### PR DESCRIPTION
**Pull request by gsfk**
can't send a dict to json.loads. :(

### CODE REVIEW

**Comment by davidlougheed** [comment]
Katsu I think will in 15.1 return an actual object instead of a JSON string for DATS, so this part of the code will need to change anyway

**Comment by davidlougheed** [comment]
(but Im not sure if bento.env has been set to use the latest katsu yet)

**Comment by gsfk** [comment]
Good! For now this makes service-info fall on its face, so needs a patch.

**Review by davidlougheed — APPROVED** [review]

**Comment by gsfk** [comment]
> (but Im not sure if bento.env has been set to use the latest katsu yet)

Yeah, I tried in 15.1 and it still falls over dead.

**Pull request merged**
