### PR TITLE
refact: use Poetry for dependencies + update

### PR DESCRIPTION
**Pull request by davidlougheed**

### CODE REVIEW

**Comment by gsfk** [comment]
Seems to work: prod mode works, debugger seems fine. Only thing new in the logs is 

```
bentov2-beacon  |   WARNING: The script pyflakes is installed in '/home/bento_user/.local/bin' which is not on PATH.
bentov2-beacon  |   Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.

```
and similar warnings for pycodestyle, normalizer, flake8, autopep8 and flask.

**Comment by gsfk** [comment]
Only issue I could find is a dangling call to pip & requirements.txt in `run.dev.bash`

**Comment by davidlougheed** [comment]
ah yes those both stem from the same issue I think, thanks for testing

**Review by gsfk — APPROVED** [review]
Thanks for this!

**Pull request merged**
