### PR TITLE
refact(utils): support new Katsu private overview response format

### PR DESCRIPTION
**Pull request by davidlougheed**

### CODE REVIEW

**Review by gsfk — CHANGES_REQUESTED** [review]
Thanks for starting this one!.

There's some broken stuff here though, since `package_biosample_and_experiment_stats()` is written with the assumption that katsu private overview has roughly the same format as katsu `api/search_overview`. See katsu pr for details.

**Comment by davidlougheed** [comment]
updated katsu... should be compatible now

**Comment by gsfk** [comment]
yes looks good

**Comment by gsfk** [comment]
almost there, only thing missing is handling for the extra nesting that's now around experiments

**Comment by davidlougheed** [comment]
oops

**Comment by gsfk** [comment]
better now, looks good

**Review by gsfk — APPROVED** [review]

**Pull request merged**
